import React, { useEffect, useState } from "react";
import { useParams, useNavigate } from "react-router-dom";
import "../App.css"

const subjectsData = {
  "Computer Science": {
    1: ["FOC NOTES", "FOC QP", "IT SKILLS MANUAL", "FEEE NOTES", "FEEE MANUAL", "ENGINEERING MATHEMATICS NOTES", "ENGINEERING MATHEMATICS QP", "ENVIRONMENT SUSTAINABILITY"],
    2: ["P.M.S NOTES", "P.M.S QP", "STATISTICS & ANALYTIC MANUAL", "C.A.E.G NOTES", "MULTIMEDIA & ANIMATION NOTES", "MULTIMEDIA & ANIMATION MANUAL"],
    3: ["PYTHON NOTES", "PYTHON MANUAL", "CN NOTES", "CN MANUAL", "HARDWARE NOTES", "HARDWARE MANUAL", "D.B.M.S NOTES", "D.B.M.S MANUAL", "KANNADA"],
    4: [ "DATA STRUCTURE WITH PYTHON MANUAL", "OPERATING SYSTEM NOTES", "OPERATING SYSTEM MANUAL", "JAVA OOPS NOTES", "JAVA OOPS MANUAL", "SOFTWARE ENGINEERING NOTES", "SOFTWARE ENGINEERING MANUAL", "INDIAN CONSTITUTION NOTES"],
    5: ["CYBER SECURITY NOTES", "CYBER SECURITY QP", "CYBER SECURITY MANUAL", "FULL STACK DEVELOPMENT TEXTBOOK"],
    6: ["CYBER SECURITY INTERNSHIP GUIDELINES", "FULL STACK DEVELOPMENT INTERNSHIP GUIDELINES"]
  },
  "Electronics & Communication": {
    1: ["DIGITAL ELECTRONICS NOTES", "FEEE NOTES", "FEEE MANUAL", "STATISTICS & ANALYTIC MANUAL", "C.A.E.G NOTES", "ENVIRONMENT SUSTAINABILITY"],
    2: ["ENGINEERING MATHEMATICS NOTES", "ENGINEERING QP", "P.M.S NOTES", "P.M.S QP", "IT SKILLS MANUAL", "ELECTRONIC COMPONENTS & DEVICES", "ELECTRONICS COMPONENTS & DEVICES MANUAL"],
    3: ["ANALOG ELECTRONICS NOTES", "LOGIC DESIGN USING VERILOG NOTES", "COMMUNICATION SYSTEM NOTES", "COMMUNICATION SYSTEM MANUAL", "ELECTRONIC MEASUREMENTS AND TESTING TECHNIQUES NOTES", "ELECTRONIC MEASUREMENTS AND TESTING TECHNIQUES MANUAL", "KANNADA"],
    4: ["PCB NOTES", "PCB MANUAL", "WIRELESS COMMUNICATION NOTES", "WIRELESS COMMUNICATION MANUAL", "EMBEDDED C PROGRAMMING NOTES", "EMBEDDED C PROGRAMMING MANUAL", "INDUSTRIAL AUTOMATION NOTES", "INDUSTRIAL AUTOMATION MANUAL", "INDIAN CONSTITUTION NOTES"],
    5: ["AUTOMATION AND ROBOTICS NOTES", "AUTOMATION AND ROBOTICS QP", "AUTOMATION AND ROBOTICS MANUAL"],
    6: ["AUTOMATION AND ROBOTICS INTERNSHIP GUIDELINES"]
  },
  "Mechanical": {
    1: ["ENGINEERING MATHEMATICS NOTES", "ENGINEERING MATHEMATICS QP", "MATERIAL FOR ENGINEERING NOTES", "MATERIAL FOR ENGINEERING QP", "C.A.E.G NOTES", "ENVIRONMENT SUSTAINABILITY"],
    2: ["MECHANICAL WORKSHOP NOTES", "MECHANICAL WORKSHOP MANUAL", "P.M.S NOTES", "P.M.S QP", "IT SKILLS MANUAL", "FEEE NOTES", "FEEE MANUAL", "STATISTICS & ANALYTIC MANUAL"],
    3: ["MECHANICS OF MATERIALS NOTES", "MECHANICS OF MATERIALS MANUAL", "MACHINE TOOL TECHNOLOGY NOTES", "MACHINE TOOL TECHNOLOGY MANUAL", "MANUFACTURING PROCESSES NOTES", "MANUFACTURING PROCESSES MANUAL", "FLUID POWER NOTES", "FLUID POWER MANUAL", "KANNADA"],
    4: ["OPERATION MANAGEMENT NOTES", "OPERATION MANAGEMENT MANUAL", "CNC PROGRAMMING NOTES", "PRODUCT DESIGN & DEVELOPMENT NOTES", "PRODUCT DESIGN & DEVELOPMENT MANUAL", "ELEMENTS OF INDUSTRIAL AUTOMATION NOTES", "ELEMENTS OF INDUSTRIAL AUTOMATION MANUAL", "INDIAN CONSTITUTION NOTES"],
    5: ["ADVANCED MANUFACTURING TECHNOLOGIES NOTES", "ADVANCED MANUFACTURING TECHNOLOGIES QP", "ADVANCED MANUFACTURING TECHNOLOGIES MANUAL"],
    6: ["ADVANCED MANUFACTURING TECHNOLOGIES INTERNSHIP GUIDELINES"]
  },
  "Automobile": {
    1: ["ENGINEERING MATHEMATICS NOTES", "ENGINEERING MATHEMATICS QP", "MECHANICAL SCIENCE NOTES", "MECHANICAL SCIENCE QP", "C.A.E.G NOTES", "ENVIRONMENT SUSTAINABILITY"],
    2: ["AUTOMOTIVE ENGINE NOTES", "AUTOMOTIVE ENGINE MANUAL", "P.M.S NOTES", "P.M.S QP", "STATISTICS & ANALYTIC MANUAL", "FEEE NOTES", "FEEE MANUAL", "IT SKILLS MANUAL"],
    3: ["AUTOMOBILE CHASSIS AND TRANSMISSION SYSTEM NOTES", "AUTOMOBILE CHASSIS AND TRANSMISSION SYSTEM MANUAL", "AUTOMOBILE ELECTRICAL AND ELECTRONIC SYSTEMS NOTES", "AUTOMOBILE ELECTRICAL AND ELECTRONIC SYSTEMS MANUAL", "AUTOMOTIVE MANUFACTURING PROCESS NOTES", "AUTOMOTIVE MANUFACTURING PROCESS MANUAL", "THERMAL ENGINEERING NOTES", "THERMAL ENGINEERING MANUAL", "KANNADA"],
    4: ["ADVANCE AUTOMOTIVE SYSTEM NOTES", "ADVANCE AUTOMOTIVE SYSTEM MANUAL", "FUELS AND POLLUTION CONTROL NOTES", "FUELS AND POLLUTION CONTROL MANUAL", "VEHICLE BODY ENGINEERING NOTES", "VEHICLE BODY ENGINEERING MANUAL", "DRAFTING NOTES", "DRAFTING MANUAL", "INDIAN CONSTITUTION NOTES"],
    5: ["FARM MACHINERY AND POWER NOTES", "FARM MACHINERY AND POWER MANUAL"],
    6: ["INTERNSHIP GUIDELINES"]
  },

  
};

const SubjectSelection = () => {
  const { branch, semester } = useParams();
  const navigate = useNavigate();
  const [subjects, setSubjects] = useState([]);

  useEffect(() => {
    if (subjectsData[branch] && subjectsData[branch][semester]) {
      setSubjects(subjectsData[branch][semester]);
    }
  }, [branch, semester]);

  return (
    <div className="flex flex-col items-center mt-10">
      <h1 className="text-2xl font-bold mb-5">Select a Subject</h1>
      <div className="grid grid-cols-2 gap-4">
        {subjects.map((subject, index) => (
          <button
          key={index}
          className="bg-purple-500 text-white p-4 rounded-lg hover:bg-purple-700"
          onClick={() =>
            navigate(`/pdf-viewer?pdf=${encodeURIComponent(subject.replace(/\s+/g, "_"))}`)
          }
        >
          {subject}
        </button>
        ))}
      </div>
    </div>
  );
};

export default SubjectSelection;
